### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by cstml**
Please refer to [issue #30 ](https://github.com/mlabs-haskell/plutus-use-cases/issues/30) for the initial description.

### CODE REVIEW

**Comment by cstml** [comment]
@stackBlock, (pending thumbs up from @Benjmhart) this is the structure I create based on  the IOHK requirements. Please pull the branch, update fields and (going forward) push to this branch - this way we can keep track of the progress in a transparent manner.

@Benjmhart please let me know if this is the structure you had in mind. If the feedback is too long to be put in writing, let's book a 10 minute conversation on Slack.

**Review by Benjmhart — APPROVED** [review]
looks great.

**Comment by stackBlock** [comment]
Thank you all for the clarifications. I have a few more questions...

1. It looks like we are delivering Lendex and the NFT project to IOHK. They are currently in the plutus-use-case/mlabs folder. Are these two projects getting pulled out of this repository and getting a repository of their own for delivery to IOHK? 
2. Based on the documentation outline, It looks like (if they are getting their own repository / file) they will be in the same repository. Is this correct?
3. Or, if they are staying where they are, are the docs just in reference to them?  I ask because my own experience in getting them (Lendex and NFT) to compile / work has been challenging but ultimately successful but a little confusing because of the other projects in the repository that  do not compile. 

I will start working on the docs assuming they are staying where they are.
Thanks,
Anthony

**Comment by Benjmhart** [comment]
@stackBlock 
 it's unclear at this time what IOHK will do with these,  after we deliver the initial effort at the end of the month, we will be building the deployment story, as well as adding performance enhancements.
currently it's all going to their repo, this is why we have the mlabs folder to namespace our work a bit and avoid conflicts,  confusingly there is also plutus-use-cases in the main `plutus` repo, it is possible that our work will eventually be merged there.

**Comment by cstml** [comment]
Good work on [817d7bb](https://github.com/mlabs-haskell/plutus-use-cases/pull/34/commits/817d7bba7919846988237bf84f2f8c72ede51139), a thorough way of going about it. 

@Benjmhart, what would be the best way to document achieved and future goals for the endpoints/APIs be? I haven't been involved in the development / previous conversations so it would be second guessing them. 
Would going over them in a conversation with you or someone else be the best way?

**Comment by Benjmhart** [comment]
> Good work on [817d7bb](https://github.com/mlabs-haskell/plutus-use-cases/pull/34/commits/817d7bba7919846988237bf84f2f8c72ede51139) @stackBlock, a thorough way of going about it.
> 
> @Benjmhart, what would the best way to document achieved and future goals for the endpoints/APIs be? I haven't been involved in the development / previous conversations so I would be second guessing them.
> Would going over them in a conversation with you or someone else be the best way?

this is one of those nonsense questions where it doesn't even make sense to me.

The API has achieved feature-completeness,  my understanding of our future goals are to work on the deployment story + performance during the next 2 months.

perhaps in the context of api, achieved goals are -it works as specified- and future goals are -none at this time- but with slightly less snark.

**Review by prutz1311 — CHANGES_REQUESTED** [review]
Lendex and NFT have both 100% test coverage but no QuickCheck tests

**Comment by cstml** [comment]
> Lendex and NFT have both 100% test coverage but no QuickCheck tests

Ok, cheers @prutz1311 for confirming, have included this.

**Comment by cstml** [comment]
> > Good work on [817d7bb](https://github.com/mlabs-haskell/plutus-use-cases/pull/34/commits/817d7bba7919846988237bf84f2f8c72ede51139) @stackBlock, a thorough way of going about it.
> > @Benjmhart, what would the best way to document achieved and future goals for the endpoints/APIs be? I haven't been involved in the development / previous conversations so I would be second guessing them.
> > Would going over them in a conversation with you or someone else be the best way?
> 
> this is one of those nonsense questions where it doesn't even make sense to me.
> 
> The API has achieved feature-completeness, my understanding of our future goals are to work on the deployment story + performance during the next 2 months.
> 
> perhaps in the context of api, achieved goals are -it works as specified- and future goals are -none at this time- but with slightly less snark.

Cheers @Benjmhart, agreed. 
Will integrate comments into the documentation

**Comment by cstml** [comment]
Received go ahead to merge.

**Pull request merged**
