### PR TITLE
Added hoogle & others into the shell

### PR DESCRIPTION
**Pull request by tavrinky**
Copied main's shell.nix, removed executables

### CODE REVIEW

**Comment by zygomeb** [comment]
@cstml this changes the dev-shell in a few different ways -- can you double check this?

**Comment by cstml** [comment]
> @cstml this changes the dev-shell in a few different ways -- can you double check this?

Reviewing at the moment.

**Comment by cstml** [comment]
@tavrinky & @zygomeb this proposal reintroduces the previous method of creating the shell. 

The current version which is present on `staging` (and which this PR changes) differs, because it checks out the working shell directly from the pinned `Plutus` version and then just adds any needed dependencies on top of that. When I set-up this newer version I thought it's more beneficial because:
- we benefit from all the changes to the official `Plutus` nix-shell at no cost
- we always have the correct nix-shell with all the needed dependencies for a `Plutus` version - guaranteed.  
- when we were working with the previous nix-shell (similarly to the one reintroduced by this PR) - it would constantly break and needed maintenance

Recommendation:
- review what is missing or needs adding to the current nix-shell and add it to this list of [dependencies](https://github.com/mlabs-haskell/plutus-use-cases/blob/d2755be2d46aef2f7db5a9956cd812e1330584e6/mlabs/shell.nix#L15) while keeping the current way of building the nix-shell
- I think there might already be a Hoogle instance inside the nix-shell - need to check that

**Comment by zygomeb** [comment]
@cstml If you could check and make Hoogle work while at it that would be great. I'm closing this PR -- Please make it a separate one,

**Comment by cstml** [comment]
Decided to give the old-structure another go, as I cannot find a good, straightforward way to isolate the `shellFor` from the Plutus derivation. Will copy to new - clean branch - and merge.

**Pull request closed without merging**
